### ISSUE TITLE
Upgrade version of git

### ISSUE THREAD

**Issue by JeroenKnoops** [philips-software/docker-node#76]
Currently the version of git does not support the use of this image in github actions.

GitHub action Checkout action needs a newer version of git.

**Comment by marcofranssen** [comment]
Seems all Dockerfile already do a `apt-get install git`.

Will a new release be sufficient to have newest git packaged, or will the apt repo require an update?

**Comment by npalm** [comment]
The image is based on stretch ( debian 9 ) which contains a quite old git version. I think we can update the base image to buster, which has debian 10 as base.

**Comment by npalm** [comment]
Just checked, buster contains by default git version 2.20.1

**Comment by bartgolsteijn** [comment]
Which is fine, as 2.18 or higher is good enough at the moment, according to https://github.com/actions/checkout.

**Comment by JeroenKnoops** [comment]
```
docker run -it philipssoftware/node:15.3.0-stretch git --version
git version 2.11.0

docker run -it philipssoftware/node:latest git --version
git version 2.20.1
```
